[yell.ow] 지하철 서비스 step3 리뷰 부탁드립니다!
next-step/spring-subway-service-kakao pull request #13
Opened 2021-01-26 00:48 UTC by idealgu

안녕하세요! 이번 지하철 서비스 미션을 제출한 옐입니다.
이번 미션은 인증 부분을 구현하는 데에 어려움이 있었습니다.. 😅

- 초기 PathController의 로그인/비로그인 여부를 Authorization Header를 포함하는 경우와 아닌 경우로 구분하여 구현하려고 했습니다. 
실제 구글 크롬에서 테스트 하는 과정에서 비로그인 시에도 Authorization : Bearer null 과 같은 헤더 정보가 포함되어 요청이 와서 AuthenticationPrincipal(required = false)로 설정하여 loginMember의 null 체크 후 로그인/비로그인 여부를 구분하도록 구현하게 되었습니다. 괜찮은 구현 방식일까요?

부족한 부분에 대한 많은 피드백 부탁드립니다! 감사합니다 😆

2021-01-26 09:51 UTC, dongjoon1251 requested changes
패키지도 잘 나누어 주시고, 각 클래스의 역할도 잘 분리해주셔서 코멘트 드릴 부분이 많지 않네요 👍 
다만 도메인과 관련된 테스트 코드를 추가해주시면 좋을 것 같습니다. 
질문 주신 부분은 코드상에 코멘트로 남겼습니다.

2021-01-26 09:51 UTC, dongjoon1251 commented on README.md
> +
기능과 커밋로그를 잘 남겨주셨네요 💯

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/line/application/LineService.java
>          return null;
null 을 리턴해서 전달하기 보다는 Optional.ofNullable을 사용해보는게 어떨까요?

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +            return null;
이부분을 질문하신것으로 파악됩니다. 
null 체크는 최대한 지양하는 것이 좋습니다.
항상 LoginMember를 리턴하고 로그인 여부를 필드로 가지거나 로그인되지 않은 사용자를 표현하는 다른 클래스로 표현해보면 어떨까요? 고민해보시고 다른 더 좋은 방법이 떠오르신다면 적용해주세요 :)

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/exceptions/AuthException.java
> +        super(message);
커스텀 예외클래스 👍 
해당 예외가 가지는 message가 항상 같다면 message를 내부의 상수로 두고 사용하면 어떨까요?

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/favorite/application/FavoriteService.java
> +    public FavoriteResponse createFavorite(LoginMember loginMember, FavoriteRequest favoriteRequest) {
request를 바로 넘겨주기보다는 파라미터가 좀 늘어나더라도 필요한 필드만 service layer로 전달하도록 리팩토링해보면 어떨까요?

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/favorite/dao/FavoriteDao.java
> +        List<Favorite> result = jdbcTemplate.query("select id, member_id, source_station_id, target_station_id from FAVORITE where id = ?", rowMapper, id);
쿼리 문자열을 상수로 분리해보면 어떨까요?

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/line/domain/Lines.java
> +        for (Line line : lines) {
addAll대신 stream의 flatMap을 사용해보면 어떨까요?

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/line/domain/Lines.java
> +        return lines.stream().mapToInt(Line::getFare).sum();
stream을 사용할 때는 가독성을 위해서 한라인에 한포인트만 남도록 줄바꿈해주세요 :)

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/line/domain/Section.java
> +    @Override
현업에서는 Object를 리턴하기보다는 generic을 사용해서 type을 최대한 명시해줍니다.
미션에 기본으로 사용된 라이브러리라서 수정하실 필요는 없고, 참고차 코멘트 남깁니다 :)

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/member/ui/MemberController.java
> +@RequestMapping("/members")
공통 패스 분리 💯

2021-01-26 09:51 UTC, dongjoon1251 commented on src/main/java/subway/path/domain/Graph.java
> +                    .collect(Collectors.toSet()));
중복을 제거하기 위해 toSet을 쓰신거라면 distinct 와 같은 메소드를 적용하고 toList로 collect해보면 어떨까요?

2021-01-27 08:14 UTC, idealgu commented
피드백 감사드립니다!! 😆
말씀해 주셨던 부분 반영해서 리팩토링을 진행해보았습니다.
처음 질문 드렸던 null 체크는 좋은 방법이 떠오르지 않아 LoginMember에 loggedIn 필드를 추가해 이를 확인하도록 적용해보았습니다.. 😢

2021-01-27 09:23 UTC, dongjoon1251 approved these changes
피드백을 잘 반영해주셨네요:)
Optional도 많은 부분에 잘 적용해주셨습니다.
추가로 코멘트를 드리자면, 테스트 코드에 실패하는 케이스들을 더 다양하게 적용해보면 좋을 것 같습니다.
이번 미션은 여기서 마무리하도록 하겠습니다. 
고생하셨습니다.

2021-01-27 09:23 UTC, merged