[turner.lee] 지하철 서비스 미션 리뷰 부탁드립니다.
next-step/spring-subway-service-kakao pull request #19
Opened 2021-01-26 06:20 UTC by sumniy

안녕하세요 리뷰어님. 터너입니다.

step3 까지 진행 후 리뷰 요청 드립니다. 잘 부탁드립니다.

2021-01-26 15:27 UTC, htrucci requested changes
안녕하세요, 터너! 아주 반가운 이름이네요😄😄
같이 지하철 서비스 미션 리뷰 하게된 데빈입니다. 
모든 기능이 정상적으로 동작하고 아주 잘 구현해주셨습니다 👍 👍 
리뷰 남겨드린 내용 한번 고민해보시고 다시 PR 부탁드립니다~! 😄

2021-01-26 15:27 UTC, htrucci commented on build.gradle
> +    runtimeOnly 'javax.xml.bind:jaxb-api:2.3.1'
혹시 이건 어떤 내용으로 추가된 걸까요?

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/AuthenticationPrincipalConfig.java
java.subway 패키지내에 Config, Controller, ExceptionHandler 등이 위치하고 있는데요.
디폴트 코드라서 그냥 두셨을수도 있지만, Application만 놔두고 나머지들은 패키지 내로 위치해주면 좋을 것 같습니다 😄

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/SubwayAdvice.java
> +}
ExceptionHandler로 잘 구현해주셨네요 👍 
다만 Advice는 너무 포괄적인 용어라서 ExceptionHandler 등으로 명명해주시는 것이 좋지 않을까요?

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/SubwayAdvice.java
> +}
ResponseEntity<Void> 타입의 Entity를 리턴하지 않고 아래 어노테이션을 붙여 동작하게 할 수 있습니다 😄 
@ResponseStatus(HttpStatus.UNAUTHORIZED)

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/auth/application/AuthService.java
> +    }
생성자 주입시 주입되는 객체가 두개 이상인 경우 생성자에 @Autowired를 붙이도록 스프링 재단에서 가이드하고 있습니다.
참고 부탁드립니다~!

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/auth/application/AuthService.java
> +    }
email만으로 db에서 password값을 가져온 후 비교하게 되면 뭐,, 가져온 password hash가 로그에 찍힐수도있고,, 
무심코 보안이슈가 생길 수 있으니, 쿼리에서 아예 패스워드까지 비교하는 방법은 어떨까요?

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/auth/application/AuthService.java
> +    }
요즘은 계정통합, 소셜계정 등으로 이메일이 중복되는 경우도 있어서 (물론 지하철 서비스는 유일하지만 ^^;;)
email말고 PK인 member.id 를 이용하여 토큰을 생성하는건 어떨까요?

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/auth/application/AuthService.java
> +    }
👍

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/auth/exception/NoSuchEmailException.java
> +}
이메일이 없는 케이스, 패스워드가 일치하지 않는 케이스 Exception나누어 상세하게 잘 구현해주셨네요. 👍 
AuthException을 상속받고 Handler로 잘 잡아서 처리해주셨다고 생각되는 부분인데
해당 메시지를 유저에게 그대로 노출해버리면 BruteForce 공격이 가능하기때문에 내부에서는 상세하게 Exception을 내더라도
유저에게 나가는 메시지는 별도로 처리되도록 유의해야합니다.  🤔 
요즘은 "아이디 및 패스워드가 일치하지 않습니다" 등 최소한으로 알려주는 추세입니다 😄

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +            return LoginMember.of(new Member(null, null, null, 20));
바로 throw new InvalidTokenException(); 해야 될 상황으로 보이는데요.
new Member(null, null, null, 20) 객체를 만들어 리턴하는게 어떤 의미가 있을까요?

>> 20세 셋팅이 필요한 것으로 요건 재확인했습니다.ㅎㅎ

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/favorite/application/FavoriteService.java
> +    }
이왕 stationDao.findById()를 한다면 insert하기전에 먼저 하면 요청된 stationId가 실제 존재하는지 유효성 검증도 같이 할 수 있겠네요. 👀

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/favorite/application/FavoriteService.java
> +        return favoriteDao.findByMemberId(memberId);
findAllByMemberId
요즘 많이 사용하는 JPA 방식에서는 좀 더 명확하게 findAll, findOne 과 같은 네이밍을 사용합니다.
미세팁으로 그냥 알고만 계시면 좋을 것 같아요
https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/favorite/dao/FavoriteDao.java
> +    }
Map params를 만들지 않고 아래 방식으로 바로 맵핑하여 넣을수도 있습니다 😄 
SqlParameterSource params = new BeanPropertySqlParameterSource(Favorite객체);

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/favorite/dao/FavoriteDao.java
> +    }
RowMapper를 써볼까요? 👀

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/favorite/dao/FavoriteDao.java
> +                "WHERE F.member_id = ?";
저도 쿼리를 짤때 성능이슈가 없다면 가능한 연관 관계를 모두 포함하여 짜곤합니다 👍 
데이터 정합성을 함께 확인할 수 있어서 좋습니다.

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/favorite/dto/FavoriteResponse.java
> +    }
💯

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +    }
서비스 호출 line이 매우 길어졌네요.
createFavorite 서비스에 FavoriteRequest를 통으로 넘기는건 어떤가요? 👀

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/line/dao/LineDao.java
> +        jdbcTemplate.update(sql, newLine.getName(), newLine.getColor(), newLine.getId());
👍

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/line/domain/Lines.java
> +}
일급컬렉션화를 잘 해주셨네요 💯

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/line/domain/SectionsInAllLine.java
> +    }
Function.identity() 는 처음 보아서 저도 찾아보았네요. 
중복을 제거한 이중 for문처럼 돌아가는군요. 잘 배웠습니다. 😄

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/path/application/PathService.java
> +    LineService lineService;
private final 을 빼먹으신 듯 하네요 😄

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/path/domain/Path.java
> +}
거리 체계와 연령별 요금체계 계산이 한 클래스에 모여있어 조금 복잡한 것 같네요.
선언된 상수들도 다소 파악하기 어렵구요 😭 
요금체계가 복잡해지면 손대기 어려운 거대한 Legacy가 될 수도 있겠어요.
PathFare와 AgeFare로 분리해보는 것은 어떨까요?

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/path/domain/SubwayEdge.java
> +    SubwayWeight weight;
protected로 선언하면 문제가 없을까요? 👀

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/path/exceptions/NotFoundPathException.java
> +    }
super가 필요하겠어요

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/path/exceptions/UnconnectedPathException.java
> +}
👍

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/path/ui/PathController.java
> +                shortestPath.getFare(loginMember.getAge()));
shortestPath.getStations()
                        .stream()
                        .map(StationResponse::of)
                        .collect(Collectors.toList()
위 코드를 PathResponse의 생성자 로직으로 옮기면 컨트롤러가 더 깔끔해질 것 같아요.
그리고 shortestPath.getFare() 를 호출하거나 하는 부분은 service레이어로 들어가는 것이 좋을 것 같아요.

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/path/ui/PathController.java
> +    }
스프링 4.3부터 단일 생성자일 경우는 @Autowired를 붙이지 않아도 됩니다.
저는 습관적으로 그냥 다 붙여주긴 합니다 👀

2021-01-26 15:27 UTC, htrucci commented on src/main/java/subway/path/ui/PathController.java
> +    }
앗, SubwayAdvice로 옮겨주세요 😄 
모든 Exception에 대한 처리면 400보다 500에러가 적합하지 않을까요?
@ApiResponse를 사용하는 부분도 고려해주세요 👍

2021-01-27 06:22 UTC, sumniy commented on build.gradle
> +    runtimeOnly 'javax.xml.bind:jaxb-api:2.3.1'
백엔드 테스트에서는 로그인 관련 기능이 정상적으로 작동하는데, 프론트에서 요청할 시에 에러가 발생해서 해결하기 위해 추가했습니다.

2021-01-27 06:28 UTC, sumniy commented on src/main/java/subway/AuthenticationPrincipalConfig.java
넵 알겠습니다!

2021-01-27 06:33 UTC, sumniy commented on src/main/java/subway/SubwayAdvice.java
> +}
말씀해주신대로 반영했습니다. 감사합니다!

2021-01-27 06:42 UTC, sumniy commented on src/main/java/subway/auth/application/AuthService.java
> +    }
아하 감사합니다.

2021-01-27 06:57 UTC, sumniy commented on src/main/java/subway/auth/application/AuthService.java
> +    }
넵 두 가지 모두 반영해보겠습니다.

2021-01-27 07:12 UTC, sumniy commented on src/main/java/subway/auth/exception/NoSuchEmailException.java
> +}
넵 참고하겠습니다. 감사합니다.

2021-01-27 07:18 UTC, sumniy commented on src/main/java/subway/favorite/application/FavoriteService.java
> +    }
그렇네요! 감사합니다.

2021-01-27 07:38 UTC, sumniy commented on src/main/java/subway/favorite/dao/FavoriteDao.java
> +    }
Member 객체가 sourceStationId, targetStationId가 아니라 sourceStation, targetStation 객체 자체를 가지고 있는 상태라서 Map을 활용해서 넣어주었는데요. 

보통 이렇게 도메인 객체가 DB 테이블 구조와 다를 때는 DB 접근용으로 별도의 Dto를 활용하는게 맞을까요? 
괜히 

그런데 보통 이렇게 도메인 객체가 DB 테이블 구조와 다를 때는 DB 접근용으로 별도의 Dto를 만들어서 활용하는게 맞을까요?
그렇게 하면 Dao에서만 사용하는 Dto 느낌이라 뭔가 과한 느낌이 듭니다..  

이 부분에 대해서 어떻게 생각하시는 지 말씀해주시면 감사하겠습니다.

2021-01-27 08:09 UTC, sumniy commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +    }
넵 가독성이 좋지 않았네요. 수정했습니다 😀

근데 관련해서 제가 MVC 패턴을 공부하다가 알게된 것에 대해서 질문드리고 싶은게 있습니다.

어떤 블로그에서 Controller에서는 request를 deserialize하고 response를 serialize 해주도록 하면, Service 계층과 Dto 간의 의존성을 분리해서 Service의 재사용성과 책임 분리가 잘 된다고 하는 글을 봤습니다.

개인적으로는 이에 반박할만한 생각이나 경험이 아직까지는 없어서 괜찮은 방법이라고 생각하고 있었는데, 주신 피드백과는 조금은 다른 방향인 것 같아서.. 실무에서는 크게 신경쓰지 않는 부분인지 아니면 어떤 규칙이 있는 것인지, 데빈은 어떻게 생각하시는지 의견 듣고 싶습니다!

2021-01-27 08:10 UTC, sumniy commented on src/main/java/subway/line/domain/SectionsInAllLine.java
> +    }
저도 페어분께 배웠습니다 ㅎㅎㅎㅎ 😆

2021-01-27 08:12 UTC, sumniy commented on src/main/java/subway/path/application/PathService.java
> +    LineService lineService;
체크 감사합니다!

2021-01-27 08:15 UTC, sumniy commented on src/main/java/subway/path/domain/Path.java
> +}
넵 분리해보겠습니다!

2021-01-27 08:23 UTC, sumniy commented on src/main/java/subway/path/domain/SubwayEdge.java
> +    SubwayWeight weight;
```
public void setEdgeWeight(E e, double weight)
    {
        assert (e instanceof DefaultWeightedEdge) : e.getClass();
        ((DefaultWeightedEdge) e).weight = weight;
    }
```
라이브러리의 일부만 상속해서 사용하느라 어떤 영향이 갈지 예측하기 힘들어서 기존 라이브러리의 코드 스타일을 따라 작성했습니다. 
이런 경우에는 저희 스타일에 맞게 수정하고 안되는 부분을 찾아 수정하는게 더 나은 방법일까요?

2021-01-27 08:24 UTC, sumniy commented on src/main/java/subway/path/exceptions/NotFoundPathException.java
> +    }
넵 반영하겠습니다.

2021-01-27 08:40 UTC, sumniy commented on src/main/java/subway/path/ui/PathController.java
> +                shortestPath.getFare(loginMember.getAge()));
넵 반영하겠습니다

2021-01-27 08:43 UTC, sumniy commented on src/main/java/subway/path/ui/PathController.java
> +    }
아하 ㅎㅎ 저도 위에서 두개 이상일 때 붙이는 가이드 알려주신거 반영하다가 다 붙이는게 일관성도 있어보이고 한눈에 보이기도 해서 다 붙였습니다 ㅎㅎ

2021-01-27 08:44 UTC, sumniy commented on src/main/java/subway/path/ui/PathController.java
> +    }
넵! 고려해보고 같이 반영해보겠습니다.

2021-01-27 15:12 UTC, sumniy commented
안녕하세요 데빈, 터너입니다.

꼼꼼하게 리뷰해주셔서 감사합니다. 

작성해주신 피드백 반영했습니다. 그리고 몇몇 피드백에 질문 남겼는데 답변 해주시면 감사하겠습니다. 🙇‍♂️

2021-01-28 01:49 UTC, htrucci commented on src/main/java/subway/favorite/dao/FavoriteDao.java
> +    }
그렇네요, 다시보니 map으로 전달한 이유를 이해했습니다.
사실 Favorite객체의 필드가 테이블과 동일하게 sourceStationId, targetStationId로 갖고있는것이
요즘 추세인 JPA ORM방식에 더 맞다고 볼 수 있고, Dto를 사용했을떄의 관리성 용이도 있겠지요.
그렇다고 Map사용이 잘못됬다는 건 아닙니다. Map의 유연함을 잘 사용해도 좋은데, FAVORITE 테이블에 관계된 데이터만 단순히 Insert하는 부분이어서 가능하면 dto가 아닌 Favorite객체 자체를 이용하는것이 어떨까 싶은 부분이네요.
추가해주신대로 getSourceStationId()를 넣어두면 현재도 SqlParameterSource params = new BeanPropertySqlParameterSource(Favorite객체); 를 적용하는데 문제는 없을 것이고 필요하다면 (enum, 랩핑클래스 사용시) 맵핑을 위해 BeanPropertySqlParameterSource 내부 함수들을 오버로딩 하는 경우도 있을 것입니다.

2021-01-28 02:24 UTC, htrucci commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +    }
말씀하신 부분이 favoriteRequest를 deserialize해서 service용 DTO로 변환해주는 내용일까요?  favoriteService.createFavorite(createFavoriteDTO)
아니면 
favoriteService.createFavorite(favoriteRequest)
favoriteService.createFavorite(loginMember.getId(), favoriteRequest.getSource(), favoriteRequest.getTarget()));
위의 차이인가요?
적어주신 내용에 크게 공감을 합니다. Controller레이어와 Service레이어 DTO 분리를 해주면 말씀해주신 장점이 있을 것 같아요.
제가 피드백 드린내용은 이거에 반하는 내용이라기보다 param이 길어지면 안좋아서 DTO로 넘겼으면 좋겠다는 의견이긴 했는데, 사실 DTO분리까지는 생각을 못하였고, Service용 DTO로 변환해주는 과정이 있다면 의존성을 분리하여 재사용성을 늘리지 않을까요?
다만 의존성 분리를 위해.. 아래와 같이 작성되는 부분도 있는데요. 많이 접하는 코드이기도 합니다 -ㅇ-;; 
이런건 지양해야 한다고 생각합니다.
Map<String, Object> favoriteService.createFavorite(Map<String,Object> paramMap)

2021-01-28 04:25 UTC, sumniy commented on src/main/java/subway/favorite/dao/FavoriteDao.java
> +    }
답변 감사합니다! 말씀해주신대로 Favorite 객체 자체로 BeanPropertySqlParameterSource를 사용하는 방식으로 수정했습니다.

2021-01-28 04:39 UTC, sumniy commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +    }
답변 감사합니다! 처음에는 그저 request, response dto만 따로 Service와 오고가지 않는 것을 생각하고 그것에 대해서만 질문을 드렸는데, 제가 너무 단순하게 질문을 드린 것 같네요 ㅎㅎ;; 말씀해주신 Service 용 Dto에 대한 생각까지는 못 했었는데 좋은 의견 말씀해주셔서 감사합니다.

2021-01-28 04:40 UTC, htrucci approved these changes
안녕하세요 터너, 데빈입니다.
리팩토링 된 부분 잘 보았습니다 👍 
특별히 추가 코멘트는 없을 것 같아 머지하도록 하겠습니다.
고생하셨습니다~! 👏

2021-01-28 04:40 UTC, htrucci commented on src/main/java/subway/member/ui/MemberController.java
>      }
미로그인 유저도 회원seq만 유추한다면 계정정보를 보거나 마음대로 삭제가 가능하겠어요.
자신의 계정만 삭제가 가능하도록 보안처리가 필요하겠네요 😄

2021-01-28 04:44 UTC, sumniy commented on src/main/java/subway/member/ui/MemberController.java
>      }
앗 정말이네요. 따로 수정하겠습니다!

2021-01-28 04:45 UTC, sumniy commented
꼼꼼한 리뷰 감사합니다~

2021-01-28 15:51 UTC, htrucci approved these changes

2021-01-28 15:51 UTC, merged

2021-02-02 01:37 UTC, htrucci commented on src/main/java/subway/path/domain/SubwayEdge.java
> +    SubwayWeight weight;
아 그렇군요 ㅎㅎ 적어주신 사유라면 잘 고려하신 것 같아요.