[joy.smile] 지하철 서비스 step3 코드 리뷰 부탁드립니다.
next-step/spring-subway-service-kakao pull request #26
Opened 2021-01-26 12:28 UTC by harim-k

안녕하세요 뉴크루 조이입니다.

- 질문
1. enum class에서 field를 public으로 선언해서 사용해도 무방한지 궁금합니다.

많은 피드백 부탁드려요 :)

2021-01-27 08:55 UTC, ljh131 requested changes
안녕하세요. 전반적으로 깔끔한 것 같습니다. 조금 더 개선할 수 있는 부분들은 커멘트 드렸습니다.

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/auth/application/AuthorizationException.java
> +public class AuthorizationException extends RuntimeException {
익셉션은 하나로 모으면 어떨까요

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/auth/ui/AuthController.java
>      // TODO: 로그인(토큰 발급) 요청 처리하기
완료되었으면 삭제해주세요

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/auth/ui/AuthController.java
> +//    POST /login/token HTTP/1.1
굳이 주석을 남기려면 어떤 의도인지 잘 표현할 수 있도록 나타내보면 어떨까요 아니면 삭제하는게 좋을 것 같습니다

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(HttpStatus.UNAUTHORIZED);
empty result인데 권한과 관련된 익셉션이면 적절하진 않을 것 같습니다.

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(HttpStatus.UNAUTHORIZED);
authentication과 authorization의 차이점을 알아보시면 좋겠습니다

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/exception/MemberNotFoundException.java
> +    public MemberNotFoundException(Long id) {
여기서 굳이 객체로 받는 이유가 있을까요

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/member/application/MemberService.java
> +            throw new AuthorizationException();
여기도 수정하는게 좋을 것 같습니다

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/map/application/MapService.java
> -public class MapService {
기본 코드인것 같은데 삭제해도 되나요?

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/path/application/PathService.java
> +    public PathResponse getPath(LoginMember loginMember, Long sourceStationId, Long targetStationId) {
get path는 하는일에 비해 너무 짧기도 하고 명확한 이름이 아닌것 같습니다.

2021-01-27 08:55 UTC, ljh131 commented on src/main/java/subway/line/domain/Line.java
> +    public Line(Long id, String name, String color, int extraFare, Sections sections) {
생성자가 꽤 많네요. 기본으로 필요한 것 외에 옵셔널한 것 때문에 상황별로 만드신 것 같습니다. 빌더 패턴, 아니면 제일 긴 생성자 외에는 줄여봐도 괜찮을 것 같은데 어떨까요

2021-01-27 08:57 UTC, ljh131 commented
> * 질문
> 
> 1. enum class에서 field를 public으로 선언해서 사용해도 무방한지 궁금합니다.

1 -> 상수가 아닌값을 퍼블릭으로 한다는 얘기신가요? final로 해도 되지만 되도록 getter를 만드는게 좋겠습니다.

2021-01-28 03:07 UTC, harim-k commented
> > * 질문
> > 
> > 
> > 1. enum class에서 field를 public으로 선언해서 사용해도 무방한지 궁금합니다.
> 
> 1 -> 상수가 아닌값을 퍼블릭으로 한다는 얘기신가요? final로 해도 되지만 되도록 getter를 만드는게 좋겠습니다.

2021-01-28 03:07 UTC, closed without merging