[ky.kiske] 지하철 서비스 미션 코드 리뷰 요청드립니다
next-step/spring-subway-service-kakao pull request #28
Opened 2021-01-26 16:12 UTC by SimJung

잘 부탁드립니다!!! 감사합니다!!

2021-01-27 05:15 UTC, sehan commented
@SimJung jgrapht-1.5 파일들이 push 되어있어서 리뷰할때 Files changed 가 너무 많아서 제가 직접제거 했습니다. ☺️

2021-01-27 06:16 UTC, sehan requested changes
안녕하세요 카이. 지하철 서비스 리뷰를 맡은 니오 입니다. ☺️
다시 만나서 반가워요~ 😉

최단이동경로찾기를 잘 구현해 주셨습니다. 하지만 인증부분 구현이 누락되어 있습니다.
요금계산기능의 경우 이동경로찾기와 함께 책임과 역할들이 한곳에 몰려 있는 부분들이 보입니다. 
그래서 수정요청 드립니다. 

관련 코멘트를 남겨 두었으니 확인 부탁드려요 ☺️

2021-01-27 06:16 UTC, sehan commented on src/main/java/subway/path/ui/PathController.java
> +        }
요청자의 연령대를 알기위해 token 에서 email 을 추출하는 코드를 직접 삽입했네요. 이렇게 집접 inline 코드를 작성하는것 보다는 교육과정에서도 언급된 AuthenticationPrincipalArgumentResolver 를 사용하여 getPaths( @AuthenticationPrincipal xxx ) 방식으로 인증정보를 받아 처리해보는 것을 권합니다. 
@AuthenticationPrincipal 을 사용하게 되면 관련 로직을 분리해 낼 수 있어서 controller 코드의 응집도가 한결 더 개선됩니다. ☺️

2021-01-27 06:16 UTC, sehan commented on src/main/java/subway/path/application/PathService.java
> +    public PathResult findShortestPath(Long sourceId, Long targetId, String email) {
PathResult 를 만들기 위한 기능이 잘 구현되어 있습니다. 👍 

여기서 Path.findShortestPath() 는 내부에서 사용중인 jgrapht 라이브러리 의존 객체를 return 해주고 있습니다. 라이브러리 의존성은 Path 내에 숨기고 외부로는 제공하지 않는것이 좋습니다. 외부로 노출시킬 수록 jgrapht 에 대한 의존성이 커지게 되어 확장성이 떨어지게 됩니다. Path 의 역할을 명확히 하고 그에 맞는 input, output 타입을 사용해 주세요.

2021-01-27 06:16 UTC, sehan commented on src/main/java/subway/path/application/PathService.java
> +        int fare = path.calculateFare(
Path 객체는 최단이동경로 와 요금계산 역할을 가지고 있습니다.  두 역할의 응집도가 높지 않아서 역할 분리가 가능해 보입니다.
역할은 분리해 보세요 ☺️

요금계산을 위한 로직을 도메인객체로 이동시켜 주세요

2021-01-27 06:16 UTC, sehan commented on src/main/java/subway/path/application/PathService.java
> +        Sections sections = sectionDao.findAll();
Data 관점에서 접근을 한다면 sectionDao.findAll() 로 접근하는게 맞습니다. 
Object 관점에서 접근한다면 lineDao.findAll() 하여 전체 노선을 가져와서 최단이동거리를 계산하기 위한 jgrapht 를 초기화 시키는 것이 더 자연스럽습니다. Line 에는 이미 Section 과 Station 객체가 모두 로딩되어 있는 상태입니다. sectionDao.findAll(), lineDao.findAll() 할 필요가 없어집니다. 

sectionDao.findAll() 하게 되면 필요한 데이터를 한번에 가져올 수 있기 때문에 데이터 접근관점에서는 효율적 입니다. 이것은 Data 접근이 필요한 그 부분에 한해서는 아주 올바른 결정입니다. 좀 더 큰 그림을 그려보면 달라 보일 수 있습니다. 최단이동거리를 구하기 위해 request 가 있을때 마다 sectionDao.findAll() , lineDao.findAll() 을 해야할까요? 데이터를 DB 에서 모두 읽어오는건 비용이 큰 작업입니다. 생각해보면 Path 가 가지고 있는 역할은 Application 내에 한번만 로딩되어 @Bean 으로 존재하고 있으면 request 가 있을때마다 DB 에서 데이터를 로딩할 필요없이 최단이동경로를 제공해 주면 됩니다.  

객체(Object) 관점으로 코드를 발전 시켜 주세요 ☺️

2021-01-27 06:16 UTC, sehan commented on src/main/java/subway/path/domain/Path.java
> +                        pathVertices.getPathVertexByStationId(section.getUpStation().getId()),
Id 를 넘기는것 보다는 Station 객체를 넘겨서 객체 비교를 통해 찾는것이 더 객체지향적인 방법입니다.

2021-01-27 06:16 UTC, sehan commented on src/main/java/subway/path/domain/PathVertices.java
> +    public void initAllVertex(List<Line> lines){
객체를 생성하는 방식으로 2가지를 제공하고 있습니다. 
```
// 1
pathV = new PathVertices()
pathV.initAllVertex(lines)

// 2
pathV = new PathVertices(pathVertexList)
```
initAllvertex() 는 2번의 경우에도 호출해서 데이터를 다시 초기화 할 위험이 있습니다. List<Line> 또는 List<PathVertex> 로 객체를 생성하기 위해 두 생성자를 private 로 만들고 static factory method 로 제공을 하는 방법도 있습니다.

2021-01-27 06:16 UTC, sehan commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +        String token = AuthorizationExtractor.extract(request);
token 으로 사용자의 인증정보(요저정보) 가 필요한 경우 inline 으로 이렇게 작성하지 말고 @AuthenticationPrincipal 어노테이션을사용해서 중복된 inline 코드들을 모두 제거해주세요

2021-01-27 06:16 UTC, sehan commented on src/main/java/subway/favorite/ui/FavoriteController.java
>  public class FavoriteController {
즐거찾기는 로그인된 (인증을 통과한 또는 인증된 token) 을 가진 요청만 허용합니다. 
interceptor 를 사용하여 접근제한을 구현해야 합니다. 

강의내용을 참고하여 interceptor 를 활용해 보세요 
https://edu.nextstep.camp/s/bb4PXLji/ls/MIOwm2me

2021-01-28 12:29 UTC, SimJung commented
리뷰 감사드립니다!! 덕분에 많은 부분을 개선할 수 있었습니다! 동시에 알아가는 즐거움도 배웠습니다 ㅎㅎ
남겨주신 코멘트를 참고하며 코드를 고치는 와중에 궁금증이 생겨 질문을 드립니다.
1. CustomArgumentResolver 내부에서 오류가 발생하면 오류를 던지고 바깥에서 핸들링을 해야할지, 아니면 그냥 null을 반환해줘야 할지 궁금합니다.
2. Path에서 전체 데이터를 한 번만 읽어오면 이후엔 데이터를 읽어올 필요가 없다는 것으로 이해했습니다. 이럴 경우 Path를 Custom bean 객체로 만들어준다는 의미인지, 이게 맞다면 이후 line 이나 section의 데이터가 변경되어도 자동으로 업데이트가 되는 것인지 궁금합니다..!
감사합니다. 좋은 하루 되세요!!! ☺️

2021-01-29 04:31 UTC, sehan requested changes
피드백을 잘 반영해 주셨습니다. 👍 👍 👍 

추가로 더 개선하면 좋을 부분들을 코멘트로 남겼습니다.
코멘트 확인 후 개선 부탁드립니다.  

수정요청드립니다. 

추가로, 도메인 객체들 단위테스트를 꼭 작성해 주세요

2021-01-29 04:31 UTC, sehan commented on src/main/java/subway/auth/ui/LoginInterceptor.java
> +    }
interceptor 를 활용한 접근권한제어 구현을 잘 해주셨습니다. 👍 

여기에 한가지 더 추가하면 더 좋을 내용이 있습니다.  jwt 를 사용하고 있기 때문에 token 에 대한 유효성 검증을 해주면 더 좋습니다.
JwtTokenProvider.validateToken() 을 사용하여 token 검증 로직을 추가해 주세요

2021-01-29 04:31 UTC, sehan commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +        Favorite favorite = favoriteService.save(loginMember.getEmail(), favoriteRequest.getSource(), favoriteRequest.getTarget());
LoginMember.getId() 로 member 의 Id 를 가져올 수 있습니다. 
favoriteService.save() 시 email 을 넘겨 다시 member 를 조회하는 것 보다는 바로 memberId 를 사용해서 save() 를 하면 됩니다.

2021-01-29 04:31 UTC, sehan commented on src/main/java/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +            return new LoginMember(member.getId(), member.getEmail(), member.getAge());
요청시 마다 token 으로 DB 에 Member 테이블을 조회해서 LoginMember 객체를 만들 수도 있지만 token 발급시 token 을 발급한 사용자의 LoginMember 객체를 만들어서 관리하면 DB 조회 없이 바로 제공해 줄 수 있습니다. 

이것은 Session 과 유사한 기능입니다. token 에 매핑되는 data 를 유지관리 할 수 있는 기능을 제공해주면 사용자정보(Member) 와 같이 빈번한 DB 요청을 줄여주어 성능개선효과를 누릴 수 있습니다. 

한번 고민해 보고 여력이 된다면 구현 해보세요 😊

2021-01-29 04:31 UTC, sehan commented on src/main/java/subway/path/ui/PathController.java
> +        PathResponse pathResponse = pathService.findShortestPath(source, target, email);
member 를 조회하기 위해 많은 곳에서 email 을 사용하고 있네요 😓
최단이동거리 요금을 계산하기 위해서는 age 만 있으면 되겠죠? LoginMember.getAge() 로 얻어 올수 있습니다.

2021-01-29 04:31 UTC, sehan commented on src/main/java/subway/member/ui/MemberController.java
> +            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
요청한 사용자정보 유무를 확인하기 위해 해당 로직이 자주 등장합니다.

이번에 추가한 LoginInterceptor 에 /members/** 관련 path pattern 을 추가해주면 인증된 요청만 controller 에 도달하기 때문에 위 로직을 제거 할 수 있습니다. 
LoginInterceptor 를 활용해서 401 처리하는 방법으로 처리해 보세요 😊

2021-01-29 04:31 UTC, sehan commented on src/main/java/subway/path/domain/Fare.java
> +public class Fare {
요금계산 역할을 잘 분리했습니다. 👍 👍 👍

2021-01-29 04:31 UTC, sehan commented on src/main/java/subway/path/domain/Fare.java
> +        fare = calculateFare(distance, extraFareList);
생성과 동시에 계산이 진행되는것 보다는 객체 생성자는 생성저 역할을 하고 이미 만들어 놓은 계산매소드로 계산 하도록 하는것이 더 좋은 객체 사용법 입니다.  객체의 모습을 보니 아마도 Fare 를 DTO 로 사용하는 동시에 요금계산 로직을 추가하다보니 그렇게 된거 같아 보이네요.  주객이 뒤바뀐거 같습니다. 😅

Fare = FareCalculator.calculate()  형태가 맞는거 같습니다.  계산과 데이터 전달을 위한 DTO 를 분리하는게 좋겠습니다.

2021-01-29 04:31 UTC, sehan commented on src/main/java/subway/path/application/PathService.java
> +            fare.discount(memberDao.findByEmail(email).getAge());
Fare 로 요금계산 로직을 분리한 것 좋았습니다. 
하지만, 아직도 노선별 추가요금을 위한 로직, 연령별 요금할인 로직이 Service 에 노출되어 있습니다. 
service 에서는 요금 계산객체에게 "path 에 대한 요금을 알려줘" 하는 형태로 끝이 나도록 개선 하면 좋겠네요
아래와 같은 형태의 코드만 남도록 개선 해주세요 😊
```
Fare fare = FareCalculator.calculator();
return new PathResponse(result, fare);
```

요금계산객체 설계시 팁을 드리자면  요금계산에 필요한 요금정책은 3개가 있습니다. 거리별요금정책, 노선별추가요금정책, 연령별요금할인정책.
요금계산시 3가지 정책을 적용하면 최종요금이 결정됩니다.  요금정책을 객체로 만들려면 어떻게 해야 할까요?
만들어진 요금정책객체들이 협력하여 최종요금을 결정하게 하려면 어떻게 해야 할까요? 

요금계산객체는 요금정책을  사용해서 요금을 결정해 주도록 구현 해보시기 바랍니다.

2021-01-29 04:31 UTC, sehan commented on src/main/java/subway/path/domain/Fare.java
> +    private final int TEEN_UPPER_BOUND = 19;
거리별 요금정책에 관련된 상태와 연령별 할인요금정책에 관련된 상태들이 Fare 에 함께 들어 있습니다. 이 부분을 분리 해 볼 수 있을거 같습니다. ☺️

2021-01-29 05:08 UTC, sehan commented
> 1. CustomArgumentResolver 내부에서 오류가 발생하면 오류를 던지고 바깥에서 핸들링을 해야할지, 아니면 그냥 null을 반환해줘야 할지 궁금합니다.

Resolver 는 request 에 담긴 요청메세지를 기반으로 argument 를 추출해주는 역할을 합니다. exception 을 던지기 보다는 null 을 반환하는것이 더 적합합니다. 반드시 필요한 필수 argument 라고 한다면 exception 을 던져서 요청메세지 검증역할로 활용할 수도 있지만 일반적으로는 null 을 return 하는 것이 적합해 보입니다.

> 2. Path에서 전체 데이터를 한 번만 읽어오면 이후엔 데이터를 읽어올 필요가 없다는 것으로 이해했습니다. 이럴 경우 Path를 Custom bean 객체로 만들어준다는 의미인지, 이게 맞다면 이후 line 이나 section의 데이터가 변경되어도 자동으로 업데이트가 되는 것인지 궁금합니다..!

Path 를 @Bean 을 사용하여 Bean 으로 등록해서 사용하라는 의도 였습니다.
Bean 으로 등록 후에는 line , section 변경이 발생할 경우 Path 를 갱신 해주는 로직이 필요합니다. 직접 구현해야 합니다. 😊

2021-01-31 11:33 UTC, SimJung commented
리뷰 및 코멘트 감사드립니다!! 꼼꼼하게 확인해주셔서 미처 신경쓰지 못했던 부분들을 개선할 수 있었습니다. 정말 감사합니다😊
Path 클래스를 Bean으로 바꾸는 과정에서 코드를 여러번 썼다지웠다 하며 고민해봤습니다만...
Bean으로 사용하게 될 때 초기화를 어떻게 해야할지, 내부에 dao를 autowired로 받아 사용하는게 맞을지 잘 모르겠습니다.
어떤식으로 생각해봐야 할지 고견을 듣고 싶습니다. 
부족한 코드지만 신경써주셔서 감사합니다!!!

2021-02-01 07:12 UTC, sehan requested changes
피드백 반영을 위해 많이 고심하셨네요 😊

요금계산역할을 객체로 잘 분리해 주셨습니다.
도메인 단위테스트 작성까지 잘 해주셨는데 아쉬운 부분들이 있어서 한번더 수정요청 드립니다.

자세한 내용은 코멘트를 확인해 주세요.

2021-02-01 07:12 UTC, sehan commented on src/main/java/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +            cache.put(token, loginMember);
발급된 token 을 관리하는 로직을 추가해 주셨네요 👍 

해당 역할을 책임질 객체는 누가 더 적합할까? 라는 생각을 더 해본다면 발급된 token 을 관리하는 로직은 token 을 발급하는 곳에 두는것이 좋겠다는 생각이 듭니다.

현재 AuthService 에서 JwtTokenProvider 를 사용하여 발급책임을 가지고 있습니다. 여기서 발급과 동시에 token 을 관리해주면 Resolver 는 argument 를 LoginMember 로 변환해주는 역할에 집중할 수 있고 그외의 로직을 authService 객체로 넘겨 줄 수 있습니다.  또한, AuthService 는 그 역할에 맞게 토큰을 발급하고 토큰의 유효성을 체크하는 것에 집중할 수 있게 됩니다.  public 메소드인 getMemberByToken 은 MemberService 에 더 어울리는 메소드 입니다.

2021-02-01 07:12 UTC, sehan commented on src/main/java/subway/auth/ui/LoginInterceptor.java
> +        }
1. JwtTokenProvider 를 주입해서 직접토큰 검증을 수행 할 수도 있지만, token 을 발급해주는 AuthService 에서 발급한 token 검증을 해주는것이 응집력 측면에서 더 좋아 보입니다.
AuthService 를 주입받아 authService.validateToken() 해주는 건 어떨까요?

2. 참고 ). 위 코드처럼 token 이 유효하지 않은경우 401 응답처리를 하기 위해 response 를 각 상황에 따라 처리하는 것도 방법입니다. 
또 다른 방법으로는 각 상황별로 response 를 처리하는 것이 아니라 response 에 대한 에러처리를  한곳에서 담당하게 하는 방법도 있습니다.  spring 에서 에러처리하는 방법들을 소개한 글 한번 살펴보세요 
https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc
https://www.baeldung.com/exception-handling-for-rest-with-spring

2021-02-01 07:12 UTC, sehan commented on src/main/java/subway/config/SubwayConfig.java
> +        registry.addInterceptor(loginInterceptor()).addPathPatterns("/members/me");
아래와 같이 다수의 pattern 을 설정하면 됩니다.
```suggestion
        registry.addInterceptor(loginInterceptor()).addPathPatterns("/favorites/**", "members/me");
```

2021-02-01 07:12 UTC, sehan commented on src/main/java/subway/path/domain/FareCalculator.java
> +    }
FareByDistance, FareByLine, FareByAge 가 FareCalculator 의 멤버라면 calculate 마다 객체를 생성하지 않아도 될거 같네요.
이렇게 되면 calculate() 매소드에서 static 을 제거할 수 있고 그에 따라 어쩔수 없이 static 으로 선언한 private 매소드들 에서도 static 을 제거 할 수 있습니다. 
꼭 static 이어야 하는게 아니라면 static 을 제거 하는것이 객체를 더 객체 답게 만들어 줍니다. ☺️
static 매소드를 작성할때 그에 부가적으로 private static 매소드들을 만들어야 하는일이 발생하게 되면 static 매소드가 맞는가? 하는 의심을 해보길 바랍니다.

2021-02-01 07:12 UTC, sehan commented on src/main/java/subway/path/domain/Path.java
> +    private LineDao lineDao;
도메인 객체에 Spring 어노테이션을 사용하는것을 도메인이 Spring 에 의존하게 만듭니다.
도메인은 spring 이 아닌 다른 프레임웍이나 다른 환경에서도 사용할 수 있는것이 재사용성, 확장성 측면에서 좋습니다.

생성자에서 List<Line> 을 받아 Path 를 생성하는것이 좋습니다.
LineDao 의존을 제거 해주세요

2021-02-01 07:12 UTC, sehan commented on src/main/java/subway/path/domain/Path.java
> +    }
PathVertex 에 List<Line> 을 추가하여 최단이동경로의 요금계산시 노선추가요금계산에 사용하는데 이로 인해 로직들이 많이 복잡해 진것이 아닌가 생각이 듭니다. 

PathVertex 를 만들어서 jgraph 에 vertex 로 추가해주는데 PathVertex 는 jgraph 에만 저장되기 때문에 Path 에서도 pathVertices 상태를 관리하게 됩니다. jgraph 의 vertex 를 구성할때 vertex 로서의 정보이외에 요금계산을 위한 데이터를 추가하여 노선추가요금 계산로직에 활용하다보니 로직이 복잡해 졌습니다. 

이를 개선하기 위해서는 노선추가요금계산 로직을 위해 추가한 List<Line> 을 PathVertex 에서 제거하고 노선추가요금은 구간정보를 입력하면 노선추가요금을 알려주는 요금테이블 데이터를 구성해 놓고 Path.findShortestPath() 의 결과를 가지고 노선추가요금을 계산하는것이 로직의 복잡도를 낮춰 줄거 같습니다.

2021-02-01 07:12 UTC, sehan commented on src/main/java/subway/config/SubwayConfig.java
> +    }
Path를 생성할때 List<Line> 을 생성인자로 받아서 생성하면 LineDao 의존을 제거 할 수 있습니다. 
```
public Path path(LineDao lineDao){
    return new Path(lineDao.findAll())
}
```

Path 는 도메인 객체이니 단위테스트를 작성해 보시면 어떤 의미인지 바로 알수 있습니다. ☺️
DB 의존때문에 단위테스트 작성이 쉽지 않을 것입니다

2021-02-01 07:12 UTC, sehan commented on src/test/java/subway/path/domain/FareByAgeTest.java
> +        assertThat(adult.getFare()).isEqualTo(3000);
요구사항에 맞게 단위테스트를 나누어서 작성해주는것이 좋습니다. 
단위테스트를 보는 것이 기능명세를 작성한다는 느낌으로 작성해주면 좋습니다. 

단위테스트에 하나의 assert 만 넣어서 작성해 보세요

2021-02-01 07:12 UTC, sehan commented on src/test/java/subway/path/domain/FareByDistanceTest.java
> +    }
거리별 요금정책을 단위테스트로 명세한다는 느낌으로 단위테스트를 추가로 작성해 주세요. 

10km 미만, 10~50km, 50km 추가시 각 상황에 맞게 결과가 나오는지 작성해 주세요

2021-02-01 07:12 UTC, sehan commented on src/test/java/subway/path/domain/FareByLineTest.java
> +        assertThat(fare.getFare()).isEqualTo(1000);
FareXXX 객체들은 모두 생성과 함께 로직이 실행되고 요금을 제공하는 DTO 역할도 수행하고 있습니다. 
DTO 와 같은 객체가 요금계산 비지니스를 가지고 있습니다. 그 부분이 테스트 코드를 보니 확실히 드러나고 있습니다. 

노선별 추가요금을 계산하는 객체라면 단위테스트에서 아래 같은 형태로 요금을 계산하는 코드 전개가 나올거 같습니다. 
```
policy = LineExtraFarePolicy( 노선구간별추가요금테이블 ) 
노선추가요금 = policy.apply( 최단이동경로 )
```

2021-02-01 07:12 UTC, sehan commented on src/test/java/subway/path/domain/PathTest.java
> +}
중요한 findShortestPath() 에 대한 테스트가 없습니다. 😅
추가해 주세요

2021-02-01 07:12 UTC, sehan commented on src/test/java/subway/path/domain/PathVerticesTest.java
> +        assertThat(pathVertices.getPathVertexByStation(s1)).isNotNull();
assertThat(pathVertices.getPathVertexList()).isNotEmpty();
not empty 체크 뿐 아니라 getPathVertexList() 에서 return 되는 List 가 vertex 를 정말 포함하고 있는지를 체크하는 것이 좋습니다.  

assertThat(pathVertices.getPathVertexByStation(s1)).isNotNull();
여기에서도 not null 뿐 아니라 실제로 기대했던 PathVertex 가 나왔는지 확인해야 합니다.

2021-02-03 18:59 UTC, SimJung commented
지난 코멘트와 리뷰 정말 감사드립니다!! 꼼꼼하게 짚어주신 부분들을 통해 배울 수 있었습니다. 감사합니다!!
말씀해주신 부분들을 바탕으로 코드를 개선해보았는데 Path 부분에서 여전히 문제가 있는 것 같아 질문 드립니다.
Config 파일에서 List를 받아 생성해주는 부분으로 변경하고 진행하다보니 비어있는 데이터가 들어오는 것을 확인했습니다.
처음부터 로드를 한 번만 하고 이후로는 추가적인 DB 조회 없이 bean으로 생성된 path 객체를 통해 최적 경로를 계산하고 싶었습니다만, 생각대로 잘 되지 않아 일단은 진행을 위해 initPath 메소드를 둔 상태입니다. 여러번 주신 힌트에도 불구하고 아직 감이 안 잡히는 것 같습니다...😭 
subwayConfig 파일에서 설정을 해줘야하는 것인지, 아니면 추가적인 어떤 과정이 필요한 것인지 알고 싶습니다.
부족한 코드지만 리뷰해주셔서 감사합니다!!!

2021-02-04 03:13 UTC, sehan approved these changes
피드백 반영 잘 해주셨습니다. 👍 

요금계산 관련 리팩토링을 위해 노력을 많이 해주셨습니다. 
단위테스트 작성도 아주 잘 되었구요. 코드도 이전보다 많이 정리가 되었습니다. 👍 👍 👍 
요금정책내부 구현시 사용된 분기문을 제거 해보는 시도를 해본다면 더 개선된 코드를 만나 보실 수 있습니다. ☺️

피드백 잘 따라와 주셔서 고맙고 감사합니다. 
남은 마지막 미션 잘 마무리하고 부서로 오는날 만나요 😊

merge 합니다.

2021-02-04 03:13 UTC, sehan commented on src/main/java/subway/auth/application/AuthService.java
> +    }
token 발급한다는 것은 해당 token 을 포함하는 요청의 경우 사용자 식별이 가능하다는 의미이기도 합니다.
사용자 식별이 되면 사용자ID 가 없어도 사용자 식별이 가능하기 때문에 접근권한체크도 가능하고 사용자정보도 매핑시킬 수 있습니다.

사용자정보의 경우 요청시 마다 자주 사용되는 항목이기 때문에 token 을 사용하여 DB 조회 없이 정보를 제공해주면 DB 조회를 줄여주는 효과를 얻을 수 있어서 token - context(사용자정보) 를 보관(cache) 해두면 좋습니다.  cache 를 멤버를 추가해서 이 부분은 잘 구현해 주셨습니다. 

cache 에 사용자정보(loginMember) 가 저장되는 시점은 token 이 발급됨과 동시에 이루어지는 것이 가장 이상적인 위치 입니다. 외부에서 putLoginMember() 사용해서 cache 에 넣어주는것보다는 AuthService 가 그 책임을 가지고 내부적으로 처리하는 것이 더 좋습니다. 그렇지 않으면 외부에서 cache 를 위해 member 객체를 만들어서 넣어줘야 하는 것을 알아야 하기 때문입니다. 
```
String accessToken = jwtTokenProvider.createToken(tokenRequest.getEmail());
cache.put(accessToken, memberDao.findByEmail(tokenRequest.getEmail());
```

이렇게 되면, token 이 invalid 한 상황이 왔을때는 cache 를 삭제하는 로직도 필요하게 됩니다. ☺️
점점 구현해야 할 사항들이 늘어나죠.  모든것들 완벽히 구현하는 것 보다는 이런 것들이 필요하겠구나? 하는 생각에 도달하기를 의도 했습니다. 고민과 깨달음을 얻은 시간이 되었기를 바랍니다. 😊

추가, 그리하여 MemberService 에 AuthService 의존을 추가하여 .getMemberByToken() 메소드를 추가한것은 상당히 부적절한 조치 입니다 😄   AuthService 에서 memberDao 를 이용하여 필요한 가져와 cache 에 넣어두고  새로운 요청에 token 이 포함되어 있는 경우 AuthenticationPrincipalArgumentResolver 가 authService 에게 token 의 context 를 요청해서(DB조회없이) 얻은 loginMember 를 controller 에 제공( return ) 해주면 됩니다.

2021-02-04 03:13 UTC, sehan commented on src/main/java/subway/path/domain/Path.java
> +    }
노선별 추가요금을 계산하기 위해 Path.getLines() 를 사용해서 전체노선을 가져오고 있는데 이부분도 Path 가 제공해줄 필요는 없어 보입니다. PathService.findShortestPath() 에서 이미 lindDao.findAll() 해서 전체노선을 가져왔기 때문에 Path 에서 꺼낼 필요 없이 바로 사용하면 해결이 됩니다. 
 
FareCalculator.calculate() 시 노선추가요금계산에 필요한 데이터를 만들기 위해 최단이동경로가 이용한 노선추가요금 목록을 만들어서 넘겨주었습니다.  이렇게 된 원인을 살펴보니 LineExtraFarePolicy 가 하는역할이 List<Integer> 를 받아 max 값을 구하는 것 밖에 없습니다. 노선추가요금에 필요한 로직들이 외부에 존재하고 내부에서는 max 값 구하는 로직만 있기 때문입니다.  노선추가요금을 계산하는 비지니스로직들이 LineExtraFarePolicy 로 이동하면 더 좋겠습니다.

2021-02-04 03:13 UTC, merged

2021-02-04 03:16 UTC, sehan commented
> 말씀해주신 부분들을 바탕으로 코드를 개선해보았는데 Path 부분에서 여전히 문제가 있는 것 같아 질문 드립니다.
> Config 파일에서 List를 받아 생성해주는 부분으로 변경하고 진행하다보니 비어있는 데이터가 들어오는 것을 확인했습니다.
> 처음부터 로드를 한 번만 하고 이후로는 추가적인 DB 조회 없이 bean으로 생성된 path 객체를 통해 최적 경로를 계산하고 싶었습니다만, 생각대로 잘 되지 않아 일단은 진행을 위해 initPath 메소드를 둔 상태입니다. 여러번 주신 힌트에도 불구하고 아직 감이 안 잡히는 것 같습니다...😭
> subwayConfig 파일에서 설정을 해줘야하는 것인지, 아니면 추가적인 어떤 과정이 필요한 것인지 알고 싶습니다.

네 맞습니다. 아직 혼돈에 빠져있는거 같습니다. 😅
```
   @Bean
    public Path path(LineDao lineDao){
        return new Path(lineDao.findAll());
# 전체노선만 생성자로 넘겨주고 생성자 내부에서 jgraph 를 만들어주는 initPath() 호출부분이 없네요
    }
```

2021-02-04 16:39 UTC, SimJung commented on src/main/java/subway/auth/application/AuthService.java
> +    }
아하... 뭔가 로직이 이상하게 늘어간다 싶으면 각 역할에 충실하지 못한 설계 덕분인 것 같습니다😂 감사합니다!!

2021-02-04 16:40 UTC, SimJung commented on src/main/java/subway/path/domain/Path.java
> +    }
같은 도메인이라도 어떤 도메인에 추가하는지도 중요하군요!!! 코멘트 감사합니다!!