[echo.ohce 김환석] 안녕하세요! 지하철 service 미션 step3 피드백 부탁드립니다.
next-step/spring-subway-service-kakao pull request #30
Opened 2021-01-27 06:15 UTC by 10000sukk

안녕하세요 저는 에코 입니다.😄 
많이 부족하지만 리뷰 주시면 정말 감사하겠습니다!

2021-01-27 06:31 UTC, parkjoos requested changes
안녕하세요 echo 😁
이번 지하철 서비스 리뷰를 맡게된 DA개발파트의 jay 라고 합니다. 
일단 본격적인 리뷰를 하기에 앞서
lib 디렉토리에 프로젝트에 포함될 필요가 없는 graph 관련 라이브러리가 통으로 들어가 있는 상태인데요
gradle 에 해당 라이브러리 디펜던시가 정의 되어 있어서 이렇게 프로젝트에 직접 추가 되지 않아도 될 것 같습니다. 해당 디렉토리 제거 후에 다시 한번 리뷰 요청 주시면 좋을것 같아요
변경된 파일이 너무 많이 나와서 실제 코드를 확인하기가 조금 어렵습니다.
그럼 확인하시고 혹시 질문 있으시면 DM 주세요

2021-01-27 06:50 UTC, 10000sukk commented
jay 안녕하세요! 라이브러리 추가 해야지 동작하는 걸로 착각했었네요...😅 감사합니다..
여기서 궁금한점이 있는데요! 혹시 gradle 에 dependency 를 추가 해주는 것만으로 라이브러리가 추가 하는 것과 동일하게 작동 하는 건가요? 아니면 다른 방식으로 동작하는 건가요? dependency 를 걸어주는 것만으로 라이브러리를 추가해 주는 것이 불필요 하다는 것은 이제 알았습니다! 혹시 답변 주시면 감사하겠습니다!

2021-01-27 06:57 UTC, parkjoos commented
build.gradle의 dependencies 항목에 필요한 디펜던시를 정의해 놓으면 
build 시에 gradle 이 필요한 라이브러리를 자동으로 다운받아 놓습니다. (build.gradle 에 repositories 에 정의된 저장소에서 다운을 받습니다.)
intellij 같은 경우 external repositories 에 다운받은 라이브러리 들이 보여지게 되어 있어요
![image](https://user-images.githubusercontent.com/61861989/105954526-21aa7400-60b8-11eb-9aad-a82ddbf27370.png)

git 에는 build.gradle 에 디펜던시가 나열된 문서만 가지고 있고 실제 라이브러리 다운로드는 이 프로젝트를 구동하는 머신에서 하도록 한다고 생각하시면 될것 같습니다.

2021-01-27 08:08 UTC, 10000sukk commented
dependency 는 그래서 깃에는 안나오는 거군요! 아하! 답변 감사드립니다😄

2021-01-28 02:08 UTC, parkjoos requested changes
echo 안녕하세요~! 😊
path 관련 로직들의 도메인이 역할이 잘 분리가 된것 처럼 보이네요 👍
다만 추가된 로직들과 도메인들에 대한 테스트 케이스가 있으면 좋을것 같은데
기존에 이미 생성되어 있는 테스트 케이스만 있네요
항상 처음 미션에 연습했던 TDD 를 습관을 들인다고 생각하고 해보면 좋을 것 같습니다.
실제 실무에서도 테스트 케이스의 중요성이 매우 큽니다.
코멘트에 몇가지 개선이 필요한 내용들을 정리해 두었습니다. 
확인 한번 부탁드립니다. 😁

2021-01-28 02:08 UTC, parkjoos commented on src/main/java/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
>          // TODO: 유효한 로그인인 경우 LoginMember 만들어서 응답하기
구현이 완료가 되었으면 TODO 코멘트 같은 코멘트는 제거해 주시는 것이 좋습니다.
이후 해당 프로젝트를 담당하는 동료나 협업자에게 혼란을 유발할 수 있습니다.

2021-01-28 02:08 UTC, parkjoos commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +    @ExceptionHandler(InvalidTokenException.class)
같은 exceptionHandler 가 각 controller 마다 붙어 있는데요 
ControllerAdvice  를 이용해서 global exception handler 클래스 하나만 정의해 좋으면 이렇게 각각 정의할 필요가 없습니다.

아래 내용을 한번 읽어 참고해 보세요, 위처럼 각 컨트롤러 단위의 제어와 ControllerAdvice 제어 두가지를 설명해 주고 있습니다. 
https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc

2021-01-28 02:08 UTC, parkjoos commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +        favoriteService.deleteFavorites(token, favoriteId);
favorite controller 에는 AuthenticationPrincipal 를 활용하지 않고 있네요 
token 스트링이 서비스 레이어 로직이나 controller 레이어에서 실제로 사용되는 경우는 거의 없습니다. 
혹시 token 이 전달되는 과정이 꼭 필요한지 확인해 보시고 
필요없다면 token 대신  AuthenticationPrincipal 정보를 확용하도록 수정해 주세요

2021-01-28 02:08 UTC, parkjoos commented on src/main/java/subway/path/application/PathService.java
> +        Path path = new Path(pathVertices, sections);
lineDao.findAll() 의 결과에 이미 각 line 별 Sections 가 있습니다. 
Section 전체를 조회 하는 과정이 꼭 필요할지 확인 부탁드립니다.

2021-01-28 02:08 UTC, parkjoos commented on src/main/java/subway/member/dao/MemberDao.java
>          String sql = "select * from MEMBER where email = ?";
이미 이렇게 작성되어 있는 부분이지만 
가능하면 쿼리들은 Constant 로 정리하고 별도로 관리 되면 좋을것 같네요
\* 프로젝션 부분도 컬럼을 명시적으로 나열하면 더 좋을 것 같습니다.

2021-01-28 02:08 UTC, parkjoos commented on src/main/java/subway/member/dao/MemberDao.java
> +        }
null  을 리턴하는 것 보다 결과를 Optional 로 wrapping 하는 방법은 어떨까요?
null 리턴은 대표적인 anti pattern 입니다. 
아래 내용 한번 참고해 보세요
https://www.codebyamir.com/blog/stop-returning-null-in-java

2021-01-28 02:08 UTC, parkjoos commented on src/main/java/subway/member/ui/MemberController.java
> +        this.jwtTokenProvider = jwtTokenProvider;
jwtTokenProvider 은 사용되지 않고 있는것 같습니다. 
필요없는 멤버는 제거해 주시면 좋을것 같습니다.

2021-01-28 02:08 UTC, parkjoos commented on src/main/java/subway/path/domain/PathVertices.java
> +    private List<PathVertex> pathVertices;
일급 컬렉션을 만들어서 역할이 많이 이관되어 좋네요!👍

2021-01-28 02:08 UTC, parkjoos commented on src/main/java/subway/path/ui/PathController.java
> +        String token = AuthorizationExtractor.extract(request);
이부분도 jwtTokenProvider 의존성이 꼭 필요한지 
token 을 직접 가져오지 않고 AuthenticationPrincipal 을 활용 할 수 없는지
고민해 보면 좋을 것 같습니다 .

2021-01-28 07:00 UTC, 10000sukk commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +    @ExceptionHandler(InvalidTokenException.class)
ControllerAdvice 를 적용하니 코드가 더 깔끔해 진듯 합니다! 감사합니다😊

2021-01-28 07:01 UTC, 10000sukk commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +        favoriteService.deleteFavorites(token, favoriteId);
앗..명심하겠습니다! 기존의 리졸버를 활용하지 못했네요 ㅜㅜ 피드백 감사합니다!

2021-01-28 07:03 UTC, 10000sukk commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +        favoriteService.deleteFavorites(token, favoriteId);
한가지 궁금한점이 있는데요! 저기서 사실 token의 유효성만을 판단하면 되기에 LoginMember로 @AuthenticationPricipal 하는 것이 적절한지 궁금합니다! 물론 @AuthenticationPrincipal 을 하면 저절로 LoginMember 로 해당 토큰에 알맞은 유저로 맵핑해주기에 유효성 검사는 되지만 더 좋은 방법이 무엇인지 질문드립니다!

2021-01-28 07:03 UTC, 10000sukk commented on src/main/java/subway/path/application/PathService.java
> +        Path path = new Path(pathVertices, sections);
앗 감사합니다!

2021-01-28 07:06 UTC, 10000sukk commented on src/main/java/subway/member/dao/MemberDao.java
>          String sql = "select * from MEMBER where email = ?";
MemberDaoQuery 라는 클래스를 만들어서 쿼리 string 값들을 상수처리 해주었습니다. 이것을 의미하신 것인지 확신이 안서서 먼저 MemberDao 만 처리해보았습니다. 이게 맞으면 다른것들도 똑같이 처리해 주도록 하겠습니다! 

프로젝션 부분 컬럼을 명시적으로 나열 한다는 말씀이 무었인지 이해를 못했습니다😅 관련된 키워드 라도 혹시 주실수 있을까요??

2021-01-28 07:07 UTC, 10000sukk commented on src/main/java/subway/member/dao/MemberDao.java
> +        }
앗...optional 쓰는 것을 놓친듯 합니다! 감사합니다!

2021-01-28 07:07 UTC, 10000sukk commented on src/main/java/subway/member/ui/MemberController.java
> +        this.jwtTokenProvider = jwtTokenProvider;
감사합니다😄

2021-01-28 07:08 UTC, 10000sukk commented on src/main/java/subway/path/domain/PathVertices.java
> +    private List<PathVertex> pathVertices;
당근 또한 감사합니다 😭😭😊

2021-01-28 07:11 UTC, 10000sukk commented on src/main/java/subway/path/ui/PathController.java
> +        String token = AuthorizationExtractor.extract(request);
이부분을 수정하기 위해서 만일 토큰이 전달되지 않았을때는 LoginMember 객체에 나이값만 Integer.MAX_VALUE로 주어서 객체를 반환해 주도록 하였습니다.. 이렇게 해도 괜찮은 건가요??

2021-01-28 07:38 UTC, parkjoos commented on src/main/java/subway/member/dao/MemberDao.java
>          String sql = "select * from MEMBER where email = ?";
@10000sukk 넵 MemberDaoQuery 에 모은것처럼 상수로 별도로 정리해 놓은걸 말한게 맞습니다 👍
프로젝션은 쿼리에서 셀렉트 구문에 어떤 컬럼을 select 할지 나열하는것을 말하는데요
지금은 * 로 전체 컬럼을 가져오겠다고 되어 있는 것을 명시적으로 전체 컬럼을 나열 해 보자고 한 것 이었습니다.

select * from MEMBER where email = ?
대신
select m.id, m.email, m.password, m.age from MEMBER m where m.email = ?

이렇게 되면 혹시 어플리케이션과 별도로 DB 상의 변경이 일어날때 어플리케이션이 영향을 받는 것도 방지 할 수 있고 코드도 더 명시적으로 보여져서 좋을 것 같습니다.

2021-01-28 08:02 UTC, parkjoos requested changes
echo 피드백 반영이 상당히 잘 된 것 같아요! 👍👍
질문에 주신 memberDao 쿼리 처럼 다른쪽들도 다 정리 해 놓으면
한번에 모아서 보기에도 편할 것 같습니다. 
프로젝션 관련 얘기는 코멘트에 달아 두었어요 (https://github.com/next-step/spring-subway-service-kakao/pull/30#discussion_r565875647)
몇가지 코멘트 추가로 드렸습니다. 함께 확인 한번 부탁드립니다.

2021-01-28 08:02 UTC, parkjoos commented on src/main/java/subway/favorite/application/FavoriteService.java
> +        favoriteDao.deleteById(favoriteId);
기존에 삭제 할 수 있는지 체크 하는 로직이 있었는데요
이 favorite 이 존재하는 favorite 인지 
지금 이 action을 하는 사람이 이 favorite 의 소유자가 맞는지 체크 하는 로직이 다시 있으면 좋겠습니다. 
그럼 질문에 주신 것처럼 MemberController 에서  AuthenticationPrincipal 로 받은 member 가 다시 필요한 녀석이 될 것 같네요

2021-01-28 08:02 UTC, parkjoos commented on src/main/java/subway/path/application/PathService.java
> +        return result;
이부분 findShortestPath 인데 요금 까지 계산하고 있으니 메소드 이름과도 맞지 않고 너무 많은 역할을 하고 있다고 느껴지네요
정확하게 findShortestPath 까지만 딱하고 요금 계산은 분리해 보면 어떨까요?
그리고 요금 계산 로직들은 이 클래스(PathService) 보다 요금 계산에만 관심을 가지는 별도의 클래스에서 수행해 보면 어떨까요?

2021-01-28 08:28 UTC, 10000sukk commented on src/main/java/subway/member/dao/MemberDao.java
>          String sql = "select * from MEMBER where email = ?";
jay 가 피드백 주신대로 전부 쿼리를 상수로 변경 완료 했습니다!

하지만 마지막에 해주신 말씀이 잘 와닿지 않는것 같습니다. 명시적으로 하면 DB 상의 변경이 일어날때 어플리케이션이 영향을 받는것을 방지한다고 하셨는데 저의 짧은 생각으로는  select * 을 했을때가 오히려 필드가 제거 되거나 필드명이 수정됬을때 받아오는 것에 더 유연하다고 생각이 듭니다😭 
어째서 명시적으로 했을때 영향을 덜 받는것인지 조금만 더 알려주신다면 정말 감사하겠습니다😂

2021-01-28 09:46 UTC, 10000sukk commented on src/main/java/subway/path/application/PathService.java
> +        return result;
Fare 클래스로 로직들을 분리 했습니다!
하지만 이것을 domin 으로 분리해야 할지 아니면 util 패키지를 새로 만들어서 분리해야 할지 고민하다가 domin의 성격이 있다고 판단해서 이를 domin 에 넣었습니다. 혹시 구분하는 팁이 있을까요??😅

2021-01-28 09:47 UTC, 10000sukk commented on src/main/java/subway/favorite/application/FavoriteService.java
> +        favoriteDao.deleteById(favoriteId);
앗..검증해줄 필요가 있을거 같습니다! 감사합니다!😄

2021-01-28 09:50 UTC, parkjoos commented on src/main/java/subway/member/dao/MemberDao.java
>          String sql = "select * from MEMBER where email = ?";
어플리케이션을 개발하다보면 DB 스키마와 도메인 객체의 모양이 달라지는 일이 발생할 수 있습니다. 
해당 DB 데이터를 한 어플리케이션에서만 사용한다면 그런 일이 별로 없을 수 있는데요 
이 데이터를 다른 어플리케이션에서도 활용한다고 하면 이 어플리케이션에서 사용할 필요가 없는 컬럼이 추가 될 수도 있습니다. 
이럴때 select * 이 어플리케이션에 있으면 실제 요청되는 데이터는 필요없는 데이터 또는 이 어플리케이션이 알지 못하는 데이터를 함께 읽어 들이게 됩니다. 
이렇게 어플리케이션이 알지 못하는 DB 변경에도 영향을 받지 않도록 애초에 필요한 컬럼만 명시적으로 select 하는것이 좀더 안정적인 어플리케이션 운영 방법으로 생각됩니다.
위 이유가 제가 생각 하는 가장 큰 이유 이고요
몇가지 더 이유가 있습니다. 아래 내용을 한번 참고 해보세요 
https://stackoverflow.com/questions/3639861/why-is-select-considered-harmful
https://medium.com/better-programming/using-select-in-an-sql-query-is-a-bad-practice-a8f6beeca1da

2021-01-28 09:54 UTC, parkjoos commented on src/main/java/subway/path/application/PathService.java
> +        return result;
다른 서비스 로직이나 dao의 의존성이 필요하다면 서비스 클래스가 맞을 것 같고 
지금처럼 그런부분이 필요 없자면 도메인 레벨이 맞을것 같아요!
아주 잘 판단하신것 같습니다. 👍

2021-01-28 10:05 UTC, parkjoos approved these changes
피드백 반영된것 잘 보았습니다. 😁
path 쪽 로직이 훨씬 가벼워졌고 
쿼리들도 각 테이블 별로 한곳으로 모이니 필요한 부분만 확인하기 훨씬 쉬워진것 같아요
쉽지 않은 과정이었는데 잘 마무리 된것 같습니다. 👍👍
이제 더 코멘트 드릴 부분이 없는것 같네요 
정말 수고 많으셨습니다. 
다음 미션도 화이팅 입니다. 👏

2021-01-28 10:05 UTC, merged

2021-01-28 14:08 UTC, 10000sukk commented
지금까지 피드백 주셔서 감사합니다!!😄 많은 도움이 되었습니다!