[danial 유기백] 지하철 서비스 pr 리뷰요청 드립니다!
next-step/spring-subway-service-kakao pull request #35
Opened 2021-01-28 08:03 UTC by Yookibaek

2021-01-28 14:23 UTC, limmmee-bonjour requested changes
안녕하세요 다니엘! 이번 미션을 함께 할 벨입니다.
깔끔하게 잘 구현해주셨네요. 그런데 pathService 부분에서 에러가 나고 있네요!
혹시 푸쉬가 덜 된건지, 제가 잘못본건지 확인 한번 부탁드려요 :)
사용되지 않는 메서드라던가, 불필요한 import는 지워주시는게 좋습니다.
추가적으로 코멘트 드렸으니 확인해보시고 문의사항 있으시면 언제든지 DM주세요.

2021-01-28 14:23 UTC, limmmee-bonjour commented on README.md
> +## 경로 조회 기능
요구사항 정의를 잘 해주셨네요 👏

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/ExceptionAdvice.java
> +    public ResponseEntity<String> catchInvalidLoginException(){
ExceptionHandler를 통해서 예외를 잘 처리해주셨네요 👍

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/auth/infrastructure/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
LoginInterceptor 생성 좋습니다 💯 👍

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/auth/infrastructure/LoginInterceptor.java
> +            throw new InvalidLoginException();
Exception에 메세지를 넣어 어떤 에러가 발생했는지 알려주면 더 좋을 것 같습니다 :)

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/favorite/dao/FavoriteDao.java
> +                    return favorite;
favorite 레퍼런스 객체를 따로 사용하지 않을거라면 바로 return 해줘도 좋을 것 같습니다~!

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/favorite/ui/FavoriteController.java
>      // TODO: 즐겨찾기 기능 구현하기
구현이 완료되었다면 TODO는 삭제해주세요 :)

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +    public ResponseEntity deleteFavorite(@PathVariable Long id){
다른 메서드와 동일하게 ResponseEntity이 어떤 반환 타입인지 명시적으로 작성해주면 좋을 것 같습니다 :)

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/line/dao/SectionDao.java
> +//            );
사용되지 않는 부분은 지워주세요 :)

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/line/dao/SectionDao.java
> +    public List<Section> findAll() {
사용하는 메서드일까요~? 사용되지 않는다면 삭제해주세요 !
추가로 필요한 import만 사용할 수 있도록 정리해주면 좋을 것 같네요.

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/path/ui/PathService.java
> +package subway.path.ui;
다른 Service는 application 패키지에 있는데, 요건 의도하신걸까요~?

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/path/ui/PathService.java
> +    private final SectionDao sectionDao;
PathService에서 sectionDao를 사용하지 않으면 지우는게 좋을 것 같아요 :) 
불필요한 의존성은 줄여주는게 좋습니다!

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/path/ui/PathService.java
> +        return new PathResponse(shortestPathStations, totalDistance, totalFare);
해당 부분은 에러가 나고 있는 것 같은데
List< StationResponse > 이 와야하는데, List< Long > 오는것 같은...
빨간불이 뜨고 있는데 혹시 푸쉬가 안된건지 확인 한번 부탁드립니다! 
```
public PathResponse(List<StationResponse> stations, int distance, int fare) {
        this.stations = stations;
        this.distance = distance;
        this.fare = fare;
    }
```

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/path/ui/PathService.java
> +        List<StationResponse> shortestStations = subwayPathGraph.getVertexList().stream()
여기 메서드에서도 subwayPathGraph 변수를 찾을 수 없다는 에러가 나네요 !

2021-01-28 14:23 UTC, limmmee-bonjour commented on src/main/java/subway/path/ui/PathService.java
> +    }
현재 요금을 계산하는 정책이 "거리", "노선별", "연령별" 정책이 존재하네요.
그런데 해당 요금을 계산하는 로직이 PathService에 존재하네요.
만약 정책이 추가되면 해당 로직을 바꾸어야겠죠? 서비스 로직은 점점 뚱뚱해지고 유연하지 못하게 될 것 같아요!
게다가 각 정책은 정책별로 기능이 정리가 되어야할 것 같아요 :)
[도전!] 자 [전략패턴](https://velog.io/@dltlsgh5/%EC%A0%84%EB%9E%B5-%ED%8C%A8%ED%84%B4strategy-pattern) 혹은 [데코레이터 패턴](https://gdtbgl93.tistory.com/9)을 적용해서 좀 더 유연한 정책코드를 만들어 봅시다!
그리고 각 정책에 관련해서는 통합테스트 뿐만 아니라 단위 테스트가 꼭 필요할것 같아요! 같이 포함시켜주세요 :)

2021-01-29 05:38 UTC, Yookibaek commented on src/main/java/subway/auth/infrastructure/LoginInterceptor.java
> +            throw new InvalidLoginException();
변경 완료 하였습니다!
익셉션에 에러를 넣는 이유는 나중에 로그를 확인하기 위함 인가요? 아니면 다른 이유도 있을까요?

2021-01-29 05:39 UTC, Yookibaek commented on src/main/java/subway/favorite/dao/FavoriteDao.java
> +                    return favorite;
수정 완료 하였습니다!

2021-01-29 05:42 UTC, Yookibaek commented on src/main/java/subway/favorite/ui/FavoriteController.java
>      // TODO: 즐겨찾기 기능 구현하기
수정 완료 했습니다!

2021-01-29 05:45 UTC, Yookibaek commented on src/main/java/subway/favorite/ui/FavoriteController.java
> +    public ResponseEntity deleteFavorite(@PathVariable Long id){
수정 완료 하였습니다!

2021-01-29 05:45 UTC, Yookibaek commented on src/main/java/subway/line/dao/SectionDao.java
> +//            );
수정 완료 하였습니다!

2021-01-29 05:46 UTC, Yookibaek commented on src/main/java/subway/line/dao/SectionDao.java
> +    public List<Section> findAll() {
수정 완료 하였습니다!

2021-01-29 05:49 UTC, Yookibaek commented on src/main/java/subway/path/ui/PathService.java
> +    private final SectionDao sectionDao;
신경을 못 썼습니다 ㅜㅜ 수정 완료 했습니다!

2021-01-29 05:49 UTC, Yookibaek commented on src/main/java/subway/path/ui/PathService.java
> +package subway.path.ui;
아닙니다! 신경을 못 썼습니다 ㅜ 수정 완료 했습니다!

2021-02-06 06:18 UTC, limmmee-bonjour commented on src/main/java/subway/auth/infrastructure/LoginInterceptor.java
> +            throw new InvalidLoginException();
익셉션에 에러메세지를 넣는 이유는 나중에 에러가 발생한 경우 트래킹을 좀 더 효율적으로 하기 위함입니다 :)!
해당 익셉션에 대해 처리할때 어떤 대상이 잘못되었는지 확인 후 처리해야하는 경우가 많습니다 :)
해당경우는 어떤 특정 유저의 토큰값이 이상한 경우가 될 수 있겠죠? 이때 메세지를 통해서 정보를 로깅하고 이를 바탕으로 해결할 수 있기때문에 좀 더 명시적인 메세지를 넣어주는게 좋습니다 :)

2021-02-08 03:22 UTC, Yookibaek commented on src/main/java/subway/path/ui/PathService.java
> +        List<StationResponse> shortestStations = subwayPathGraph.getVertexList().stream()
해당 에러 수정 완료 하였습니다!

2022-11-05 07:22 UTC, closed without merging